package com.penguinmagic.cardsgeneratorlib.model.cards


enum class CardsSuitEnum {
    CLUB_KING, CLUB_QUEEN, CLUB_JACK, CLUB_ACE, CLUB_10, CLUB_9,
    CLUB_8, CLUB_7, CLUB_6, CLUB_5, CLUB_4, CLUB_3, CLUB_2,

    DIAMOND_KING, DIAMOND_QUEEN, DIAMOND_JACK, DIAMOND_ACE,
    DIAMOND_10, DIAMOND_9, DIAMOND_8, DIAMOND_7, DIAMOND_6,
    DIAMOND_5, DIAMOND_4, DIAMOND_3, DIAMOND_2,

    HEART_KING, HEART_QUEEN, HEART_JACK, HEART_ACE, HEART_10,
    HEART_9, HEART_8, HEART_7, HEART_6, HEART_5, HEART_4, HEART_3, HEART_2,

    SPADE_KING, SPADE_QUEEN, SPADE_JACK, SPADE_ACE, SPADE_10, SPADE_9,
    SPADE_8, SPADE_7, SPADE_6, SPADE_5, SPADE_4, SPADE_3, SPADE_2;

}